name = "teia-proxy"
main = "src/index.js"
compatibility_date = "2022-08-28"

[vars]
TARGET_HOSTNAME = "teia.art"
HICDEX_API = "https://api-v5.teia.rocks/v1/graphql"
IPFS_GATEWAY = "https://nftstorage.link/ipfs/"
